<a href="https://colab.research.google.com/github/2303A52095/generativeAI_2025/blob/main/2303a52095_week_1_Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 1. (1 ponto) Write Python code from scratch to find error metrics of deep learning model. Actual
 values and deep learning model predicted values are shown in Table 1. Also compare the results
 with the outcomes of libraries

In [21]:
import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
Y_actual = np.array([20, 30, 40, 50, 60])
Y_pred = np.array([20.5, 30.3, 40.2, 50.6, 60.7])
n = len(Y_actual)
mae_scratch = sum(abs(Y_actual - Y_pred)) / n
mse_scratch = sum((Y_actual - Y_pred) ** 2) / n
rmse_scratch = np.sqrt(mse_scratch)
r2_scratch = 1 - (sum((Y_actual - Y_pred) ** 2) / sum((Y_actual - np.mean(Y_actual)) ** 2))

print("Error Metrics Calculated from Scratch:")
print(f"Mean Absolute Error (MAE): {mae_scratch}")
print(f"Mean Squared Error (MSE): {mse_scratch}")
print(f"Root Mean Squared Error (RMSE): {rmse_scratch}")
print(f"R-Squared (R2): {r2_scratch}")

mae_lib = mean_absolute_error(Y_actual, Y_pred)
mse_lib = mean_squared_error(Y_actual, Y_pred)
rmse_lib = np.sqrt(mse_lib)
r2_lib = r2_score(Y_actual, Y_pred)

print("\nError Metrics Using Libraries:")
print(f"Mean Absolute Error (MAE): {mae_lib}")
print(f"Mean Squared Error (MSE): {mse_lib}")
print(f"Root Mean Squared Error (RMSE): {rmse_lib}")
print(f"R-Squared (R2): {r2_lib}")

Error Metrics Calculated from Scratch:
Mean Absolute Error (MAE): 0.4600000000000016
Mean Squared Error (MSE): 0.24600000000000147
Root Mean Squared Error (RMSE): 0.49598387070549127
R-Squared (R2): 0.99877

Error Metrics Using Libraries:
Mean Absolute Error (MAE): 0.4600000000000016
Mean Squared Error (MSE): 0.24600000000000147
Root Mean Squared Error (RMSE): 0.49598387070549127
R-Squared (R2): 0.99877


 2. (1 ponto) Write python code from scratch to find evaluation metrics of deep learning model.
 Actual values and deep learning model predicted values are shown in Table 2. Also compare the
 results with outcome of libraries

• Expected Leaning Outcomes from this assignment related to python– Students are able to understand deep learning model metrics– Students are able to write code in python to find deep learning model metrics– Students are abl

In [22]:
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
Y_actual = np.array([0, 0, 0, 0, 0, 0, 1, 1, 2, 2, 1, 1, 2, 0, 2, 0, 2, 2, 1, 0, 2, 2, 2, 2])
Y_pred = np.array([0, 0, 0, 1, 2, 2, 1, 0, 2, 0, 2, 0, 2, 2, 2, 1, 2, 2, 2, 0, 2, 2, 2, 2])
def calculate_metrics_from_scratch(y_actual, y_pred):
    unique_classes = np.unique(np.concatenate((y_actual, y_pred)))
    conf_matrix = np.zeros((len(unique_classes), len(unique_classes)), dtype=int)
    for a, p in zip(y_actual, y_pred):
        conf_matrix[a][p] += 1

    accuracy = np.trace(conf_matrix) / np.sum(conf_matrix)

    precisions = []
    recalls = []
    f1_scores = []
    for i in range(len(unique_classes)):
        tp = conf_matrix[i][i]
        fp = sum(conf_matrix[:, i]) - tp
        fn = sum(conf_matrix[i, :]) - tp
        precision = tp / (tp + fp) if (tp + fp) > 0 else 0
        recall = tp / (tp + fn) if (tp + fn) > 0 else 0
        f1 = 2 * (precision * recall) / (precision + recall) if (precision + recall) > 0 else 0

        precisions.append(precision)
        recalls.append(recall)
        f1_scores.append(f1)

    avg_precision = np.mean(precisions)
    avg_recall = np.mean(recalls)
    avg_f1 = np.mean(f1_scores)

    return accuracy, avg_precision, avg_recall, avg_f1, conf_matrix

accuracy_scratch, precision_scratch, recall_scratch, f1_scratch, conf_matrix_scratch = calculate_metrics_from_scratch(Y_actual, Y_pred)

print("Evaluation Metrics Calculated from Scratch:")
print(f"Accuracy: {accuracy_scratch}")
print(f"Precision (Macro-Averaged): {precision_scratch}")
print(f"Recall (Macro-Averaged): {recall_scratch}")
print(f"F1 Score (Macro-Averaged): {f1_scratch}")
print("Confusion Matrix:")
print(conf_matrix_scratch)

accuracy_lib = accuracy_score(Y_actual, Y_pred)
precision_lib = precision_score(Y_actual, Y_pred, average='macro')
recall_lib = recall_score(Y_actual, Y_pred, average='macro')
f1_lib = f1_score(Y_actual, Y_pred, average='macro')
conf_matrix_lib = confusion_matrix(Y_actual, Y_pred)

print("\nEvaluation Metrics Using Libraries:")
print(f"Accuracy: {accuracy_lib}")
print(f"Precision (Macro-Averaged): {precision_lib}")
print(f"Recall (Macro-Averaged): {recall_lib}")
print(f"F1 Score (Macro-Averaged): {f1_lib}")
print("Confusion Matrix:")
print(conf_matrix_lib)

Evaluation Metrics Calculated from Scratch:
Accuracy: 0.5833333333333334
Precision (Macro-Averaged): 0.5158730158730158
Recall (Macro-Averaged): 0.5148148148148147
F1 Score (Macro-Averaged): 0.5
Confusion Matrix:
[[4 2 3]
 [2 1 2]
 [1 0 9]]

Evaluation Metrics Using Libraries:
Accuracy: 0.5833333333333334
Precision (Macro-Averaged): 0.5158730158730158
Recall (Macro-Averaged): 0.5148148148148147
F1 Score (Macro-Averaged): 0.5
Confusion Matrix:
[[4 2 3]
 [2 1 2]
 [1 0 9]]
